VAIBHAVBABELE/vaibhavbabele.github.io

gallery.html
game/game.html
game/space/space-shooter.html
game/sps/sps.html
game/tictac/tic.html
gateway.html
index.css
index.html
index.js
paper.html
quantum.html
resorces.html
subject.html

now dark mode apply on all pages at same time

update dark mode

---

announcement-table.htm
index.css
index.html
user-experience-table.html

🔖 PR Title:
Fix: UI issues in announcement and user experience tables (Closes #16, #17)
📄 Description:
This pull request fixes the UI-related  improvement and the user experience for the announcement and user experience tables. It also includes backend preparation using PHP for future database integration.
✅ Documentation 📝
✅ UI/UX Update 🎨
✅ enhancement
https://github.com/user-attachments/assets/694295a2-3f04-41f5-9f37-c50f1282d13d
🧑‍💻 What changes were made?
1. Removed Google Script-based embedding and replaced with standard HTML src files named: anouncement-table.htm and user-experience-table.html in iframes.
2. Ensured table UI works properly across devices (responsive fix).
3. Added commented PHP code for future database access (currently inactive, serves as a reference or …

Fix: UI issues in announcement and user experience tables (Closes #16, #17)

---

index.html
pr-contributors.html

[Feature]: Add PR Showcase Page with Contributors, GsSOC
---
This PR adds a new `pr-contributors.html` page to showcase all the contributors who have created Pull Requests under GsSOC. The feature includes a structured and styled layout for better visibility and UI presentation.
---
- Created `pr-contributors.html` page.
- Added contributor details dynamically.
- Linked the new page to `index.html` for navigation.
---
---
> 📸 Attach **screenshot or screen recording** showing the updated section (mandatory for UI/UX or visible changes).
---
- HTML / CSS
- JavaScript 
---
Closes #62 
---
---
None.

[Feature]: Add PR Showcase Page with Contributors, GsSOC 

---

RESUME/index.html
announcement-table.htm
index.html
user-experience-table.html

---
Made Both Tables Responsive
Added Media Queries for small screens
---
> Issue #84 
https://github.com/user-attachments/assets/b2838461-7f2d-407c-94fd-8cd8775b4954

Optimized the tables for small screens

---

gallery.html
index.js
privacy.html
terms.html

1.Enhanced Terms&conditions and Privacy Policy
2.Fixed Typo error in Footer
---
---
- Added Terms and Conditions Page
- Fixed Typo Error in Footer
---
---
---
Closes #102
---
---

Upd footer

---

index.css

Enhancement of Image Hover Effect in Gallery.
---
---
- Enhanced hover effects of images in gallery.
---
---
- Before changes : 
https://github.com/user-attachments/assets/983a54b0-e460-40c3-ad44-563459b5352b
- After Changes :
https://github.com/user-attachments/assets/e26a57fc-9196-4dfc-9cb2-7197dee91b14
---
---
Closes #IssueNumber :  #28
---
---
NONE

Enhancement of Image Hover Effect in Gallery.

---

games/hangman.html
games/memory.html
games/quiz.html
games/typing.html
index.css
pr-contributors.html
privacy.html
terms.html

Fixed the excessive gap issue in the top panel/navbar on mobile view across all pages. Implemented comprehensive mobile-first responsive design with proper navbar sizing, eliminated unwanted white space, and improved hamburger menu alignment for better user experience.
---
- Reduced navbar height from 80px to 60px (desktop) and optimized for mobile (55px/50px).
- Fixed hamburger menu alignment and centering on all screen sizes.
- Removed excess white space between the navbar and main content.
- Added hover effects and smooth transitions for a better user interface.
- Implemented mobile-first responsive design with breakpoints: `1000px`, `772px`, `450px`.
- Consolidated and cleaned up navbar styling across all pages.
- Resolved margin conflict between `.main` and `.main-page`.
---
---
> ✅ …

Fix navbar mobile responsive design and eliminate excessive gaps

---

cursor.css
cursor.js
index.html

Added snake trail cursor animation with mobile detection
---
Implemented a smooth snake-like cursor animation using trailing dots. Also added detection to disable on mobile/touch devices for performance and UX.
---
- Added a smooth snake trail cursor animation using JavaScript and CSS.
- Created cursor.js and cursor.css files for modular and clean implementation.
- Implemented mobile/touch detection using window.matchMedia to disable animation on small or touch devices.
---
---
> 📸 Attach **screenshot or screen recording** showing the updated section (mandatory for UI/UX or visible changes).
https://github.com/user-attachments/assets/8e7de0e6-dadd-4ba9-ab6c-7a7fff7ad637
---
---
Closes #79 
---

Added snake trail cursor animation with mobile detection

---

index.css
index.html

Enhanced text content and corrected script placement
---
---
- Corrected the placement of script tag for visitors count
- Enhanced content across all pages
- Added new sections in About us
---
no
---
> 📸 Attach **screenshot or screen recording** showing the updated section (mandatory for all changes).
---
HTML / CSS / JavaScript
---
index.html
index.css
Closes #135 
---
- [ x] Frontend 🎯
- [x ] UI/UX 🎨
- [x ] Bug Fix 🐛
---

fix: Enhanced text content and corrected script placement

---

games/gamess.html
games/hangman.html
games/memory.html
games/quiz.html
games/typing.html
index.html
index.js
pages/404.html
pages/announcement-table.html
pages/assistant/assistant.css
pages/assistant/assistant.html
pages/certificate/certificate.html
pages/cgpa-calculator.html
pages/contact.html
pages/gallery.html
pages/gateway.html
pages/infrastructure.html
pages/paper.html
pages/pr-contribution/pr-contributors.html
pages/privacy.css
pages/privacy.html
pages/quantum.html
pages/resorces.html
pages/subject.html
pages/summary/summary.css
pages/summary/summary.html
pages/summary/summary.js
pages/terms.html
pages/test.html
pages/user-experience-table.html

Fixed resource page link and CSS path issue
---
- [ ✅] Enhancement 🔧
---
- Fixed broken link on Resources page.
- Corrected CSS file path so styles load properly.
- Minor HTML cleanup for better readability.
---
-  Yes, I have updated the relevant section in `README.md` or related files.
---
> 
- PHP / MySQL
- Tailwind / Bootstrap 
Closes #IssueNumber 
---
- [✅ ] Frontend 🎯

Fixed resource page link and CSS path issue

---

CODE_OF_CONDUCT.md

Added Comprehensive Code of Conduct for NITra MITra | GSSoC’25
---
This PR adds a fully detailed and formal Code of Conduct for the NITra MITra project, ensuring a safe, inclusive, and respectful environment for all contributors under GSSoC’25 guidelines.
---
- Created a detailed Code of Conduct document for NITra MITra.
- Added sections for Community Values, Zero Tolerance, Contributor Expectations, and Reporting Process.
- Expanded vision and commitment statements to align with project goals.
- Adapted from Contributor Covenant v3.0 with NITra MITra-specific modifications.
---
---
---
- PHP / MySQL
- Tailwind / Bootstrap 
- Other: **Markdown Documentation**
---
> Closed Issue #237 
---
---
This Code of Conduct ensures that NITra MITra remains a professional, …

Add CODE_OF_CONDUCT.md | GSSoC'25 Documentation

---

CODE_OF_CONDUCT.md
README.md

---
- Updated README.md to include a clear project overview.
- Added tech stack details and setup instructions.
---
- updated readme
- add gssoc logo
---
---
---
- PHP / MySQL
- Tailwind / Bootstrap 
- Other: Markdown
---
> Closed Issue #250 
---
---

update readme with gssoc logo

---

README.md

Added gssoc logo

---

README.md

sorry div problem create kr rha tha
last merge, then close it
DONT GIVE POINTS HERE

dont need to add points

---

pages/contact.css
pages/contact.html

Enhanced contact page.
---
This PR enhances the contact page UI by:
- Separating the heading of Get in touch of the page clearly with rest of page by changing its appearance with respect to the rest of the page.
- Adding an input field if the other is selected as a subject from the dropdown, which will only be visible if the other is selected from the dropdown.
- Added flip card functionality to the contact information
- Added emojis in each heading and subheading in the page to make it look more fun.
---
- Changing the appearance of the main heading of the page
- Adding an input field that is only visible when "other" is selected in the subject
- Added flipping functionality in cards in the contact information section
- Added emojis for each heading and subheading
---
--- …

Enhanced contact page

---

pages/paper.css
pages/resorces.html
pages/tech.html
pages/tech.js

Added downloadable tech notes
---
---
- added in resourced diff tech notes
- users can preview notes and download them.
---
---
https://github.com/user-attachments/assets/f471d22b-b410-486d-a2dd-79f9d663ce54
---
---
resorces.html
paper.css
tech.html
tech.js
Closes #262 
---
---
I am a GSSoC contributor!

Added downloadable tech notes

---

games/games.css
index.css

**📄Description**:
This PR improves the overall readability and alignment of game cards in Dark Mode. The card titles and inner text in Gallery were barely visible in dark mode, so their font size, weight, and color have been updated along with a subtle text-shadow for clarity. Additionally, adjustments were made to the game container item alignment to ensure proper spacing and consistent layout across all screen sizes.
-  Bug Fix ✅
-  Enhancement 🔧
- 
**🧑‍💻What changes were made?**
-  Fixed card title visibility in Dark Mode with better contrast color.
-  Improved readability of game description text using text-shadow in Dark Mode.
-  Corrected card overlap/alignment issue in Games section.
**📸  Before showing improved Dark Mode readability and fixed card alignment.** …

fix: corrected card alignment and improved Dark Mode text visibility

---

index.css

---
Enhanced color contrast for calculator tabs and results section in dark mode for better readability. Fixed visibility of refresh icon. Ensured no changes affect the light theme
- [✅] Enhancement 🔧
---
- Strengthened dark mode tab text and background colors
- Improved result box contrast in dark mode
- Enhanced refresh icon visibility in dark mode
- Ensured light theme remains unaffected
---
---
---
---
- index.css
Closes #IssueNumber 
---
- [✅] Frontend 🎯
- [✅] Enhancement🪄
---
No breaking changes; this improves accessibility and dark mode experience.
Thank you !!

fix: improve dark mode accessibility for calculator tabs and results

---

index.css
pages/announcement-table.html
pages/user-experience-table.html

Fixed Responsiveness of website sections on smaller screens
##📄 Description:
This PR improves the responsiveness of website sections on smaller screens.
1. Centered the “Welcome to Nitra Mitra” heading to align with the hero section.
2. Fixed misalignment in the “Student Announcements” section.
3. Adjusted text alignment in the “User Experience” section.
4. Added responsive media queries for smaller screen widths.
**BEFORE : **
**AFTER :**
1. index.css
2. announcement-table.html
3. user-experience-table.html
Closes #295
-Frontend 🎯
Visual balance maintained across different screen sizes.

Fix: Responsiveness of website sections on smaller screens

---

pages/footer.css
pages/privacy.css
pages/privacy.html

Privacy policy redesigned
---
I have redesigned the privacy policy page and made it consistent to the theme of all the other sections, made changes in the footer section of the page so that the section remains visually consistent to the section, added some extra text so that it is practical.
---
- Changed the css of the privacy section
- Removed the teams section as it does not belong to the privacy page
- Increased the size of the links footer
- Add some extra text as for the privacy policy
---
---
> 📸 Attach **screenshot or screen recording** showing the updated section (mandatory for all changes).
---
---
privacy.html, privacy.css, footer.css
Closes #317 
---
---
Contributing under OSCI'25

Privacy policy redesigned

---

pages/terms.css
pages/terms.html
pages/terms.js

🔖 PR Title:
Fixed missing navigation bar on Terms and Conditions page and made and made the ui of the Terms page consistent with other pages using external css and js.
📄 Description:
This PR fixes the issue where the Terms and Conditions page was missing the global navigation bar, leading to a poor and inconsistent user experience. With this update, the Terms and Conditions page now includes the same navigation header present on all other pages, ensuring seamless navigation across the site.
✔️ Bug Fix
🧑‍💻 What changes were made?
Added the global navigation bar to the Terms and Conditions page.
Ensured consistent header structure across all pages.
Minor UI alignment fixes for the Terms and Conditions page.
Implemented styling and interactions using external CSS and JavaScript for …

Updated terms final[OSCI'25]

---

pages/contact.html
pages/contact.js

The form was accepting black value... which I had fixed
---
---
- 
- 
- 
---
---
> 📸 Attach **screenshot or screen recording** showing the updated section (mandatory for all changes).
---
- HTML and JavaScript
---
Closes #348 
---
---
@VAIBHAVBABELE  Please review it and merge it

Form validation added

---

games/games.css
games/gamess.html
games/hangman.html
games/quiz.html

Enhanced Games Section with Tab-Switching Feature
---
This PR enhances the existing Games section by implementing a tab-based navigation system. Instead of loading games separately, users can now switch between multiple games on a single page, improving both usability and overall experience.
-  New Feature ✨
- Enhancement 🔧
- UI/UX Update 🎨
---
- Implemented tab-switching functionality to display different games within one page.
- Updated layout for better organization of multiple games.
- Improved UI consistency across the Games section.
---
---
- gamess.html
- games.css
Closes #351
---
-  Frontend 🎯
- UI/UX 🎨
- Feature Implementation 🚀
- Optimization ♻️
---

enhanced games section

---

index.css
index.html

- Complete redesigning of Nitra Mitra educational platform Landing page for a modern ui.
---
Transformed the Landing page of Nitra Mitra platform into a better styled page for enhanced user experience.
[ ] Bug Fix ✅
[ ] New Feature ✨
[ ✅ ] Enhancement 🔧
[ ] Documentation 📝
[ ✅ ] UI/UX Update 🎨
---
-  Changed the font color for better visibility 
-  Added hover animation and icons on service section cards for modern look
-  Enhanced the Announcement Section made it a grid for better spacing and added hover animation on the cards
-  Enhanced the User Experience Section and added hover animation on the cards
-  Enhanced the About section with highlighted headings
-  Used colored icons and added a icon in the submit feedback button for better ui
---
---
- After Changes …

Redesigned landing page with new layout

---

index.css
index.html
index.js
pages/ai-assistant.html
pages/cgpa-calculator.html
pages/contact.css
pages/feedback.html
pages/gateway.html
pages/infrastructure.html
pages/paper.css
pages/paper.html
pages/placement-updates.html
pages/placement.css
pages/product-list.html
pages/scholarship.css
pages/student-marketplace.css
pages/student-marketplace.html
pages/subject.html
pages/tech.html

Improved dark mode with smooth transitions, better UX, and accessibility features.
- **Smooth Transitions**: Added CSS transitions for all color/background changes
- **Better Animations**: Enhanced mode toggle with rotation/scale effects
- **System Integration**: Auto-detects and follows OS theme preferences
- **Accessibility**: Added keyboard support and ARIA labels
- **Performance**: Optimized animations with no impact on speed
- Premium theme switching experience
- Full accessibility compliance
- Seamless system integration
- Enhanced user satisfaction
- `index.css` - Enhanced transitions
- `index.js` - Improved theme logic  
- `index.html` - Added accessibility
The dark mode now provides a smooth, professional experience that rivals modern web applications.

Fix minor chanhes and seamless dark mode transition 

---

FONT_STYLING_FIX_SUMMARY.md
css/typography.css
index.css
index.html
pages/summary/summary.css
pages/syllabus/syllabus.css
pages/terms.css
pages/terms.html

- Multiple font families scattered: Lora, Poppins, Segoe UI, Raleway, Cinzel
- Google Fonts imported multiple times
- No consistent typography hierarchy
- px, rem, em, vw, clamp() used inconsistently
- Sizes ranging from 11px to 8rem
- Poor responsive scaling
- Font properties scattered in HTML style attributes
- CSS files with redundant font declarations
- No centralized typography system
- **Primary Font**: Inter (clean, modern sans-serif)
- **Secondary Font**: Merriweather (elegant serif for headings)
- **Responsive Sizing**: clamp() for all font sizes
- **Consistent Hierarchy**: h1-h6 with proper scaling
- **Utility Classes**: Font weights, sizes, and special text styles
- **Accessibility**: High contrast, reduced motion support
- **Dark Mode**: Optimized font rendering
```css …
```

corrected fonts and added a sumarry of changes
